### ISSUE TITLE
Template versions with ractive 0.8.12

### ISSUE THREAD

**Issue by fiskgrodan** [ractivejs/rvc#18]
Hello i used the **rvc** require compoenent loader plugin with ractive@0.8.12

It gave an error about TEMPLATE_VERSION was 4 and not the expected 3. (The latest version of the rvc was made in 2015 and is probably made for ractive@0.7.3)

I changed the "var TEMPLATE_VERSION = 3;" to a "var TEMPLATE_VERSION = 4;" in the rvc.js file(line 353) and it seems to work correctly. Do you think it can cause any issues or side effects?

**Comment by fskreuz** [comment]
The problem is that rvc has not been updated lately. It uses an older version of rcu, which expects 0.7.3. Newer rcu actually uses 0.8.0. So in the meantime, you can fork rvc, update the rcu dependency and see if it checks out. Then use your fork in the meantime.

The related PR to the version 4 bump should be https://github.com/ractivejs/ractive/pull/2369. A quick glance on the test hints that it's got to do with the new decorator (`as-*`) and transitions (`*-in`, `*-out`, `*-in-out`) among other things. If you don't use those new features, it _might_ be ok to manually bump rvc's expected template version.

There are plans to update the plugins and tools, that is, if we get the time to work on it. 🤞

**Comment by p3k** [comment]
Any update on this?

**Comment by fskreuz** [comment]
I'll look into this later today.

**Comment by fskreuz** [comment]
@p3k Can you point `rvc` to the `edge` branch to check? May I also know if you use Bower or npm. I have not published the build to npm yet, in case you're wondering.

**Comment by p3k** [comment]
Downloaded rvc.js from the dist directory in the edge branch – works so far without any issue. Thanks! :+1: 

(Are all those changes necessary just to bump the template version?)

**Comment by fskreuz** [comment]
> Are all those changes necessary just to bump the template version?

Sort of. Was actually a cascade of sorts.

- A template version bump means the AST generated by `Ractive.parse()` is no longer structurally similar to previous versions and may cause your tool to break. 
- rvc depends on rcu, which in turn depends on Ractive. An older rcu means your tool expects an older Ractive to go with it. The warning happens when either one (usually the tool) is outdated.
- rcu no longer does a default export and instead, exports per function. `* as rcu` was probably the least invasive fix. 
- The other changes were for tooling, ensuring the build and tests still run.

I don't have access to npm to publish this yet, hence the edge branch. I also only have the existing tests as my guards, I have no app to test this against. Will probably let it soak a week or two before publishing and tagging this as a new release.

**Comment by p3k** [comment]
Oh wow, there’s quite some levels involved…

Anyway, thanks for your help – if you would add another comment here whenever the npm package is ready, I would appreciate it.

**Comment by fskreuz** [comment]
Finally had time to get to this. Repo and npm should now be updated.
